// <auto-generated />
using System;
using MF.Repository.Configurations.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MF.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230428181831_usuarioAlt")]
    partial class usuarioAlt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("MF.Domain.Commons.Consumirdores.Consumidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdConsumidor");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RendaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Consumidor", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.Empresas.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdEmpresa");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CnpjEmpresa")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Endereço")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCondPagto");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("Credito")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("QuantParc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CONDPAGTO", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.Parcs.CondPagtoParcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCondPagtoParcs");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCondPagto")
                        .HasColumnType("int");

                    b.Property<int>("SeqParc")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorParc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCondPagto");

                    b.ToTable("CONDPAGTOPARC", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.FormaPagtos.FormaPagto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdFormaPagto");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("FORMAPAGTO", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Despesas.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdDespesa");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCondPagto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoConsumidor")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoEmpresa")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CodigoFormaPagto")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<bool>("Mensal")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCondPagto");

                    b.HasIndex("CodigoConsumidor");

                    b.HasIndex("CodigoEmpresa");

                    b.HasIndex("CodigoFormaPagto");

                    b.HasIndex("ConsumidorId");

                    b.ToTable("DESPESA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("CCF")
                        .HasColumnType("text");

                    b.Property<string>("COO")
                        .HasColumnType("text");

                    b.Property<int?>("CodigoCondPagto")
                        .HasColumnType("integer");

                    b.Property<int?>("CodigoEmpresa")
                        .HasColumnType("integer");

                    b.Property<int?>("CodigoFormaPagto")
                        .HasColumnType("integer");

                    b.Property<int?>("CondPagtoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FormaPagtoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotalDescontos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotalItens")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTributos")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CondPagtoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FormaPagtoId");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.Desconto.DescontoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoItemCompra")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CodigoItemCompra")
                        .IsUnique();

                    b.ToTable("DescontoItem");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCompra")
                        .HasColumnType("integer");

                    b.Property<int?>("CodigoDesconto")
                        .HasColumnType("integer");

                    b.Property<int>("CompraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<int>("SequencialItem")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotalItem")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("ItemCompra");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.MarcaItens.MarcaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoItem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("MarcaItem");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Rendas.Renda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdRenda");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("CodigoConsumidor")
                        .HasColumnType("integer")
                        .HasColumnName("CodigoConsumidor");

                    b.Property<int?>("CodigoEmpresa")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Salario")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConsumidor");

                    b.HasIndex("CodigoEmpresa");

                    b.ToTable("RENDA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Itens.MetaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoMeta")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpectativaAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiferencaCompraReserva")
                        .HasColumnType("numeric");

                    b.Property<string>("LinkCompra")
                        .HasColumnType("text");

                    b.Property<int>("MetaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorGuardarMes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorReservaCompra")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("MetaItem");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoConsumidor")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataIniVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotalCompra")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotalGuardado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ConsumidorId");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.Parcs.CondPagtoParcs", b =>
                {
                    b.HasOne("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", null)
                        .WithMany("Parcs")
                        .HasForeignKey("CodigoCondPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Despesas.Despesa", b =>
                {
                    b.HasOne("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", "CondPagto")
                        .WithMany()
                        .HasForeignKey("CodigoCondPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", "Consumidor")
                        .WithMany()
                        .HasForeignKey("CodigoConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("CodigoEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.ModalidadePagto.FormaPagtos.FormaPagto", "FormaPagto")
                        .WithMany()
                        .HasForeignKey("CodigoFormaPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", null)
                        .WithMany("Despesas")
                        .HasForeignKey("ConsumidorId");

                    b.Navigation("CondPagto");

                    b.Navigation("Consumidor");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPagto");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Compra", b =>
                {
                    b.HasOne("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", "CondPagto")
                        .WithMany()
                        .HasForeignKey("CondPagtoId");

                    b.HasOne("MF.Domain.Commons.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("MF.Domain.Commons.ModalidadePagto.FormaPagtos.FormaPagto", "FormaPagto")
                        .WithMany()
                        .HasForeignKey("FormaPagtoId");

                    b.Navigation("CondPagto");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPagto");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.Desconto.DescontoItem", b =>
                {
                    b.HasOne("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", "ItemCompra")
                        .WithOne("DescontoItem")
                        .HasForeignKey("MF.Domain.ControleMensal.Mercado.Compras.Itens.Desconto.DescontoItem", "CodigoItemCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCompra");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", b =>
                {
                    b.HasOne("MF.Domain.ControleMensal.Mercado.Compras.Compra", "Compra")
                        .WithMany("Itens")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.MarcaItens.MarcaItem", b =>
                {
                    b.HasOne("MF.Domain.ControleMensal.Mercado.Itens.Item", "Item")
                        .WithMany("MarcaItens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Rendas.Renda", b =>
                {
                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", "Consumidor")
                        .WithMany("Rendas")
                        .HasForeignKey("CodigoConsumidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DESPESA_CONSUMIDOR");

                    b.HasOne("MF.Domain.Commons.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("CodigoEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Consumidor");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Itens.MetaItem", b =>
                {
                    b.HasOne("MF.Domain.Planejamento.Meta", "Meta")
                        .WithMany("Itens")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Meta", b =>
                {
                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", "Consumidor")
                        .WithMany()
                        .HasForeignKey("ConsumidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("MF.Domain.Commons.Consumirdores.Consumidor", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Rendas");
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", b =>
                {
                    b.Navigation("Parcs");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Compra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", b =>
                {
                    b.Navigation("DescontoItem")
                        .IsRequired();
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.Item", b =>
                {
                    b.Navigation("MarcaItens");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Meta", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
