// <auto-generated />
using System;
using MF.Repository.Configurations.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MF.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("MF.Domain.Commons.Consumirdores.Consumidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("CELULAR");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("RendaTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RENDA_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("CONSUMIDOR", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.Empresas.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("CnpjEmpresa")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("CNPJ_EMPRESA");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<string>("Endereço")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ENDEREÇO");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NOME_EMPRESA");

                    b.HasKey("Id");

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("Credito")
                        .HasColumnType("boolean")
                        .HasColumnName("CREDITO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("QuantParc")
                        .HasColumnType("int")
                        .HasColumnName("QUANT_PARC");

                    b.HasKey("Id");

                    b.ToTable("CONDPAGTO", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.Parcs.CondPagtoParcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCondPagto")
                        .HasColumnType("int")
                        .HasColumnName("ID_COND_PAGTO");

                    b.Property<int>("SeqParc")
                        .HasColumnType("int")
                        .HasColumnName("SEQ_PARC");

                    b.Property<decimal>("ValorParc")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_PARC");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCondPagto");

                    b.ToTable("CONDPAGTOPARC", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.FormaPagtos.FormaPagto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("FORMAPAGTO", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Despesas.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCondPagto")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_COND_PAGTO");

                    b.Property<int>("CodigoConsumidor")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_CONSUMIDOR");

                    b.Property<int?>("CodigoEmpresa")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_EMPRESA");

                    b.Property<int>("CodigoFormaPagto")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_FORMA_PAGTO");

                    b.Property<int?>("ConsumidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("date")
                        .HasColumnName("DATA_DESPESA");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("date")
                        .HasColumnName("DATA_FINAL");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("date")
                        .HasColumnName("DATA_INICIAL");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("Mensal")
                        .HasColumnType("boolean")
                        .HasColumnName("MENSAL");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("integer")
                        .HasColumnName("TIPO_DESPESA");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCondPagto");

                    b.HasIndex("CodigoConsumidor");

                    b.HasIndex("CodigoEmpresa");

                    b.HasIndex("CodigoFormaPagto");

                    b.HasIndex("ConsumidorId");

                    b.ToTable("DESPESA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("CCF")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CCF");

                    b.Property<string>("COO")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("COO");

                    b.Property<int?>("CodigoCondPagto")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_COND_PAGTO");

                    b.Property<int?>("CodigoEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_EMPRESA");

                    b.Property<int?>("CodigoFormaPagto")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_FORMA_PAGTO");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("date")
                        .HasColumnName("DATA_COMPRA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.Property<decimal>("ValorTotalDescontos")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR_TOTAL_DESCONTOS");

                    b.Property<decimal>("ValorTotalItens")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR_TOTAL_ITENS");

                    b.Property<decimal>("ValorTributos")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR_TRIBUTOS");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCondPagto");

                    b.HasIndex("CodigoEmpresa");

                    b.HasIndex("CodigoFormaPagto");

                    b.ToTable("COMPRA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.Desconto.DescontoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoItemCompra")
                        .HasColumnType("int")
                        .HasColumnName("ID_ITEM_COMPRA");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_DESCONTO");

                    b.HasKey("Id");

                    b.HasIndex("CodigoItemCompra")
                        .IsUnique();

                    b.ToTable("DESCONTOITEM", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoCompra")
                        .HasColumnType("INT")
                        .HasColumnName("CODIGO_COMPRA");

                    b.Property<int?>("CodigoDesconto")
                        .HasColumnType("INT")
                        .HasColumnName("CODIGO_DESCONTO");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("QUANT");

                    b.Property<int>("SequencialItem")
                        .HasColumnType("INT")
                        .HasColumnName("SEQ_ITEM");

                    b.Property<decimal>("ValorTotalItem")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL_ITEM");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_UNIT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCompra");

                    b.ToTable("ITEMCOMPRA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("ITEM", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.MarcaItens.MarcaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoItem")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_ITEM");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoItem");

                    b.HasIndex("ItemId");

                    b.ToTable("MARCAITEM", (string)null);
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Rendas.Renda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoConsumidor")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_CONSUMIDOR");

                    b.Property<int?>("CodigoEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_EMPRESA");

                    b.Property<int?>("ConsumidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("Salario")
                        .HasColumnType("boolean")
                        .HasColumnName("SALARIO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConsumidor");

                    b.HasIndex("CodigoEmpresa");

                    b.HasIndex("ConsumidorId");

                    b.ToTable("RENDA", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Itens.MetaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoMeta")
                        .HasColumnType("INT")
                        .HasColumnName("CODIGO_META");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataExpectativaAquisicao")
                        .HasColumnType("date")
                        .HasColumnName("DATA_EXPECTATIVA_AQUISICAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("DiferencaCompraReserva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DIFERENCA_COMPRA_RESERVA");

                    b.Property<string>("LinkCompra")
                        .HasMaxLength(900)
                        .HasColumnType("varchar")
                        .HasColumnName("LINK_COMPRA");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_COMPRA");

                    b.Property<decimal>("ValorGuardarMes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_GUARDAR_MES");

                    b.Property<decimal>("ValorReservaCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_RESERVA_COMPRA");

                    b.HasKey("Id");

                    b.HasIndex("CodigoMeta");

                    b.ToTable("METAITEM", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoConsumidor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("date")
                        .HasColumnName("DATA_FIM_VIGENCIA");

                    b.Property<DateTime?>("DataIniVigencia")
                        .HasColumnType("date")
                        .HasColumnName("DATA_INI_VIGENCIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorTotalCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL_COMPRA");

                    b.Property<decimal>("ValorTotalGuardado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_TOTAL_GUARDADO");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConsumidor");

                    b.ToTable("META", (string)null);
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.Parcs.CondPagtoParcs", b =>
                {
                    b.HasOne("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", null)
                        .WithMany("Parcs")
                        .HasForeignKey("CodigoCondPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Despesas.Despesa", b =>
                {
                    b.HasOne("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", "CondPagto")
                        .WithMany()
                        .HasForeignKey("CodigoCondPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", "Consumidor")
                        .WithMany()
                        .HasForeignKey("CodigoConsumidor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("CodigoEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.ModalidadePagto.FormaPagtos.FormaPagto", "FormaPagto")
                        .WithMany()
                        .HasForeignKey("CodigoFormaPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", null)
                        .WithMany("Despesas")
                        .HasForeignKey("ConsumidorId");

                    b.Navigation("CondPagto");

                    b.Navigation("Consumidor");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPagto");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Compra", b =>
                {
                    b.HasOne("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", "CondPagto")
                        .WithMany()
                        .HasForeignKey("CodigoCondPagto");

                    b.HasOne("MF.Domain.Commons.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("CodigoEmpresa");

                    b.HasOne("MF.Domain.Commons.ModalidadePagto.FormaPagtos.FormaPagto", "FormaPagto")
                        .WithMany()
                        .HasForeignKey("CodigoFormaPagto");

                    b.Navigation("CondPagto");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPagto");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.Desconto.DescontoItem", b =>
                {
                    b.HasOne("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", "ItemCompra")
                        .WithOne("DescontoItem")
                        .HasForeignKey("MF.Domain.ControleMensal.Mercado.Compras.Itens.Desconto.DescontoItem", "CodigoItemCompra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemCompra");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", b =>
                {
                    b.HasOne("MF.Domain.ControleMensal.Mercado.Compras.Compra", "Compra")
                        .WithMany("Itens")
                        .HasForeignKey("CodigoCompra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.MarcaItens.MarcaItem", b =>
                {
                    b.HasOne("MF.Domain.ControleMensal.Mercado.Itens.Item", "Item")
                        .WithMany()
                        .HasForeignKey("CodigoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MF.Domain.ControleMensal.Mercado.Itens.Item", null)
                        .WithMany("MarcaItens")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Rendas.Renda", b =>
                {
                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", "Consumidor")
                        .WithMany()
                        .HasForeignKey("CodigoConsumidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MF.Domain.Commons.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("CodigoEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", null)
                        .WithMany("Rendas")
                        .HasForeignKey("ConsumidorId");

                    b.Navigation("Consumidor");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Itens.MetaItem", b =>
                {
                    b.HasOne("MF.Domain.Planejamento.Meta", "Meta")
                        .WithMany("Itens")
                        .HasForeignKey("CodigoMeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Meta", b =>
                {
                    b.HasOne("MF.Domain.Commons.Consumirdores.Consumidor", "Consumidor")
                        .WithMany()
                        .HasForeignKey("CodigoConsumidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consumidor");
                });

            modelBuilder.Entity("MF.Domain.Commons.Consumirdores.Consumidor", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Rendas");
                });

            modelBuilder.Entity("MF.Domain.Commons.ModalidadePagto.CondPagtos.CondPagto", b =>
                {
                    b.Navigation("Parcs");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Compra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Compras.Itens.ItemCompra", b =>
                {
                    b.Navigation("DescontoItem");
                });

            modelBuilder.Entity("MF.Domain.ControleMensal.Mercado.Itens.Item", b =>
                {
                    b.Navigation("MarcaItens");
                });

            modelBuilder.Entity("MF.Domain.Planejamento.Meta", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
